socialmedia/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from connect.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Front,name='front'),
    path('login/',Login,name="login"),
    path('logout/',Logout,name="logout"),
    path('Register/',Register,name="register"),
    path('in/<str:Username>/',UserProfile,name="UserProfile"),
    path('in/Edit/<str:Username>/', Update_User_Details, name = "UpdateUserProfile"),
    path('all_companies',Companies,name="companies"),
    path('contact/',Contact,name="contact"),


    path('all_professionals/<str:what>/',All_Profession,name="professional"),
    path('connection/<str:action>/<int:u_id>/',Manage_your_connections, name="connections"),
    path('add_company/', Add_Company, name = "addCompany"),
    path('company_details/<int:c_id>', CompanyDetails, name = "CompanyDetails"),
    path('post_new_blog/', NewPost, name = "post"),
    path('likes/<int:b_id>/<str:Username>/', Like_By_Me, name = "likes")
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

connect/models.py
from django.db import models
from django.contrib.auth.models import User

class UserDataBase(models.Model):
    usr = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=120,null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    number = models.IntegerField(null=True,blank=True)
    image = models.ImageField(null=True,blank=True)
    about = models.TextField(null=True,blank=True,)
    dob = models.DateField(null=True,blank=False)
    location = models.CharField(max_length=150,null=True,blank=True)
    Degree = models.CharField(max_length=150,null=True,blank=True)
    website = models.CharField(max_length=150,null=True,blank=True)
    experience = models.CharField(max_length=150,null=True,blank=True)
    company = models.CharField(max_length=150,null=True,blank=True)
    profile_title=models.CharField(max_length=150,null=True,blank=True)

    def __str__(self):
        return self.name

class connections(models.Model):
    sender = models.ForeignKey(UserDataBase,related_name="sender",on_delete=models.CASCADE,null=True,blank=True)
    receiver = models.ForeignKey(UserDataBase,related_name="receiver",on_delete=models.CASCADE,null=True,blank=True)
    status = models.CharField(max_length=30,null=True,blank=True,default="sent")
    date = models.DateField(auto_now_add=True,null=True)

    def __str__(self):
        return "{} send request to {}".format(self.sender, self.receiver)


class Company_Model(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    logo = models.ImageField(null=True, blank=True)
    number = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)
    website = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    title = models.CharField(max_length=100, null=True, blank=True)
    map_embad = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name
class Blogs_Model(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    blog = models.TextField(null=True, blank=True)
    youtube_video = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)



class BlogLikes(models.Model):
    usr = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    blog = models.ForeignKey(Blogs_Model, on_delete=models.CASCADE, null=True, blank=True)

connect/forms.py
from django import  forms
from .models import *

class AddUser_Form(forms.ModelForm):
    class Meta:
        model = UserDataBase
        exclude = ("usr","dob","location","Degree","website","experience","company")
        widgets={
            "name":forms.TextInput(attrs={"class":"form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "number": forms.NumberInput(attrs={"class": "form-control"}),
            "image": forms.FileInput(attrs={"class": "form-control","onchange":"loadFile(event)"}),
            "about": forms.Textarea(attrs={"class": "form-control","rows":"5"})

        }
class Edit_User_Details(forms.ModelForm):
    class Meta:
        model = UserDataBase
        exclude = ("usr",)
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control", }),
            "email": forms.EmailInput(attrs={"class": "form-control", }),
            "number": forms.NumberInput(attrs={"class": "form-control", }),
            "about": forms.Textarea(attrs={"class": "form-control", "rows": "5"}),
            "location": forms.TextInput(attrs={"class": "form-control", }),
            "Degree": forms.TextInput(attrs={"class": "form-control", }),
            "website": forms.TextInput(attrs={"class": "form-control", }),
            "experience": forms.TextInput(attrs={"class": "form-control", }),
            "company": forms.TextInput(attrs={"class": "form-control", }),
            "profile_title": forms.TextInput(attrs={"class": "form-control", }),
            "dob": forms.DateInput(attrs={"class": "form-control"})
        }

class StartCompany_Form(forms.ModelForm):
    class Meta:
        model = Company_Model
        exclude = ("usr",)
        widgets = {
            "name":forms.TextInput(attrs={"class":"form-control", }),
            "website":forms.TextInput(attrs={"class":"form-control", }),
            "address":forms.TextInput(attrs={"class":"form-control", }),
            "title":forms.TextInput(attrs={"class":"form-control", }),
            "map_embad":forms.Textarea(attrs={"class":"form-control", }),
            "email":forms.EmailInput(attrs={"class":"form-control", }),
            "number":forms.NumberInput(attrs={"class":"form-control", }),
            "logo":forms.FileInput(attrs={"class":"form-control","onchange":"loadFile(event)" }),

        }


class UserBlog_Form(forms.ModelForm):
    class Meta:
        model = Blogs_Model
        exclude = ("usr",)
        widgets = {
            "title":forms.TextInput(attrs={"class":"form-control", }),
            "youtube_video":forms.Textarea(attrs={"class":"form-control", }),
            "blog":forms.Textarea(attrs={"class":"form-control", })
        }

connect/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User
from django.http import HttpResponse
from .forms import *
from django.db.models import Q
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import get_template
from django.conf import settings


def Sendmailold(email, msg):
    from_email = settings.EMAIL_HOST_USER
    to_email = [email]
    html = get_template("mail.html").render({"msg":msg})
    #html = "<h1>Email</h1>"
    sub = "Thank you For your Registration on Social on"
    send_mail(sub, " ", from_email, to_email, html_message=html)


def Front(request):
    if request.user.is_authenticated:
       return redirect("UserProfile",request.user.username)
    companies=""
    companies = Company_Model.objects.all()
    Dict= {
        "data":companies
    }
    return render(request,'index.html',Dict)


def Login(request):
    if request.user.is_authenticated:
       return redirect("UserProfile",request.user.username)
    form=AddUser_Form()
    error = False
    if request.method == "POST":
        un = request.POST["un"]
        ps =  request.POST["ps"]
        usr = authenticate(username=un,password=ps)
        if usr!=None:
            login(request,usr)
            return redirect("UserProfile",usr.username)
        error=True
    Dict={
        "error":error,"form":form
        }
    return render(request,'login_register.html',Dict)



def Register(request):
    if request.method == "POST":
        form = AddUser_Form(request.POST,request.FILES)
        if form.is_valid():
            data=form.save(commit=False)
            un=request.POST["un"]
            ps=request.POST["ps"]
            email=data.email
            usr=User.objects.create_user(un,email,ps)
            data.usr=usr
            data.save()
            msg = "Hi,{name}, Thank You for your interest in Social on Project,It is just learning purpose project".format(name=un)
            print(email)
            print(msg)
            Sendmailold(email,msg)
            return redirect('login')
            error = True
    return HttpResponse("Register Your Self")



def Logout(request):
    logout(request)
    return redirect("front")


def UserProfile(request,Username):
    if not request.user.is_authenticated:
        return redirect("login")
    usr = User.objects.filter(username=Username)
    if not usr:
        loggen_in_username=request.user.username
        return redirect('UserProfile',loggen_in_username)
    connection = None
    if request.user.username != Username:
        user1 = User.objects.get(username = Username)
        user2 = User.objects.get(username=request.user.username)
        UserData1 = UserDataBase.objects.get(usr = user1)
        UserData2 = UserDataBase.objects.get(usr = user2)
        connection = connections.objects.filter\
            (Q(sender=UserData1, receiver=UserData2) | Q(sender=UserData2, receiver=UserData1))
        if connection:
            connection = connection[0]
    Usr=usr[0]
    user_detail=UserDataBase.objects.get(usr=Usr)
    blog_form = UserBlog_Form()
    all_post = Blogs_Model.objects.filter(usr = Usr).order_by("-date")
    like_by_me_Ids = []
    all_likes_by_me = BlogLikes.objects.filter(usr=request.user)
    for i in all_likes_by_me:
        like_by_me_Ids.append(i.blog.id)
    Dict={
        "profile":user_detail,"connection":connection,"form":blog_form,"posts":all_post,"like_by_me_Ids":like_by_me_Ids
    }
    return render(request,"user_details.html",Dict)


def Update_User_Details(request, Username):
    if not request.user.is_authenticated:
        return redirect("login")

    loggen_in_username = request.user.username
    if Username != loggen_in_username:
        return redirect("UserProfile", loggen_in_username)

    usr = User.objects.filter(username=Username)
    Usr = usr[0]
    User_Detail = UserDataBase.objects.get(usr=Usr)

    form = Edit_User_Details(request.POST or None, request.FILES or None, instance=User_Detail)
    if form.is_valid():
        form.save()
        return redirect("UserProfile", loggen_in_username)

    Dict = {
        "Profile": User_Detail, "form":form
    }
    return render(request, "Update_User_Details.html", Dict)



def All_Profession(request, what):
    if not request.user.is_authenticated:
        return redirect("login")

    logged_in_user = User.objects.get(username = request.user.username)
    me = UserDataBase.objects.get(usr=logged_in_user)
    ###### Count Request Section #########
    con_request = connections.objects.filter(receiver=me, status="sent")
    con_sent = connections.objects.filter(sender=me, status="sent")
    con_friend = connections.objects.filter(Q(sender=me, status="friend") | Q(receiver=me, status="friend")).order_by( "-date")

    #-----X Count Request Section End ---X_------#
    data = ""
    if what == "all":
        data = UserDataBase.objects.all()
    if what == "myreceived":
        connection = connections.objects.filter(receiver=me, status = "sent")
        User_Data = []
        for c in connection:
            ud = UserDataBase.objects.get(id = c.sender.id)
            User_Data.append(ud)
        data = User_Data
    if what == "Sent":
        connection = connections.objects.filter(sender=me, status = "sent")
        User_Data = []
        for c in connection:
            ud = UserDataBase.objects.get(id=c.receiver.id)
            User_Data.append(ud)
        data = User_Data
    if what == "Friends":
        connection = connections.objects.filter(Q(sender=me, status = "friend") | Q(receiver=me, status = "friend")).order_by("-date")
        Data = []
        for c in connection:
            UserData = UserDataBase.objects.get(id = c.sender.id)
            if UserData.id != me.id:
                Data.append(UserData)

            UserData = UserDataBase.objects.get(id=c.receiver.id)
            if UserData.id != me.id:
                Data.append(UserData)
            data = Data
    Dict = {
        "all_users":data, "what":what, "con_request":con_request, "con_sent":con_sent,
        "con_friend":con_friend
    }
    return render(request, "professionals.html", Dict)



def Manage_your_connections(request,action,u_id):
    if not request.user.is_authenticated:
        return redirect("login")
    if action == "Send_Request":
        senderUser=User.objects.get(username = request.user.username)
        sender = UserDataBase.objects.get(usr = senderUser)
        receiver = UserDataBase.objects.get(id = u_id)
        connections.objects.create(sender = sender,receiver = receiver)
        return redirect('UserProfile',receiver.usr.username)
    if action == "Accept_Request" or action == "Reject_Request":
        ReceiverUser = User.objects.get(username=request.user.username)
        receiver = UserDataBase.objects.get(usr=ReceiverUser)
        sender = UserDataBase.objects.get(id=u_id)
        connection = connections.objects.filter(sender=sender, receiver=receiver)
        if connection:
            for c in connection:
                if action == "Accept_Request":
                    c.status = "friend"
                    c.save()
                if action == "Reject_Request":
                    c.status = "rejected"
        return redirect("professional", "all")
    return HttpResponse("you want" + str(action) +"for user" + str(u_id))


def Add_Company(request):
    if not request.user.is_authenticated:
        return redirect("login")
    form = StartCompany_Form()
    if request.method == "POST":
        form = StartCompany_Form(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            Map = data.map_embad
            if 'width="600"' in Map:
                Map = Map.split('width="600"')
                Map.insert(1, 'width="100%"')
                Map = " ".join(Map)
                data.map_embad = Map
            data.usr = request.user
            data.save()
            return redirect("login")
    Dict = {
        "form":form
    }
    return render(request, "add_company.html", Dict)

def Companies(request):
    if not request.user.is_authenticated:
        return redirect("login")
    companies = Company_Model.objects.all()
    Dict = {
        "companies":companies
    }
    return render(request,"companies.html",Dict)


def CompanyDetails(request,c_id):
    if not request.user.is_authenticated:
        return redirect("login")

    company = Company_Model.objects.get(id = c_id)
    if not company:
        return redirect("companies")
    print(company)
    Dict = {
        "company":company
    }
    return render(request, "companies_detail.html",Dict)


def NewPost(request):
    if request.method == "POST":
        form = UserBlog_Form(request.POST)
        if form.is_valid():
            data = form.save(commit = False)
            data.usr = request.user
            data.save()
            print("Blog Submitted...@")
    return redirect("login")


def Like_By_Me(request, b_id, Username):
    if not request.user.is_authenticated:
        return redirect("login")
    blog = Blogs_Model.objects.get(id=b_id)
    BlogLikes.objects.create(usr=request.user, blog=blog)
    return redirect("UserProfile", Username)

def Contact(request):
    return render(request,"contact.html")

connect/templates/Update_User_Details.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <!-- Content -->
  <div id="content">

    <!-- Papular Companies -->
    <section class="padding-bottom-100">
      <div class="compny-profile user-profile">
        <!-- SUB Banner -->
        <div class="profile-bnr">
          <div class="container">

            <!-- User Iinfo -->
            <div class="user-info">
              <div class="">
                <div class="user-in">
                  <div class="pro-avatar"> <img src="{{ Profile.image.url }}" height="200" alt="" class="img-responsive" > </div>
                  <h1>{{ Profile.name }}  </a> </h1>
                  <h6>Professional Designer and Front-end developer</h6>

                  </div>
              </div>
            </div>
          </div>

          <!-- Modal POPUP -->
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <h6><a class="close" href="#." data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></a> Send Message</h6>
                <!-- Forms -->
                <form action="#">
                  <ul class="row">
                    <li class="col-md-6">
                      <input type="text" placeholder="First Name" class="form-control">
                    </li>
                    <li class="col-md-6">
                      <input type="text" placeholder="Last Name" class="form-control">
                    </li>
                    <li class="col-md-6">
                      <input type="text" placeholder="Country" class="form-control">
                    </li>
                    <li class="col-md-6">
                      <input type="text" placeholder="Email" class="form-control">
                    </li>
                    <li class="col-md-12">
                      <textarea placeholder="Your Message" class="form-control"></textarea>
                    </li>
                    <li class="col-md-12 text-center">
                      <button class="btn">Send message</button>
                    </li>
                  </ul>
                </form>
              </div>
            </div>
          </div>
        </div>

        <!-- Profile Company Content -->
        <div class="profile-company-content main-user">
          <div class="container">

            <!-- Nav Tabs -->
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li><a class="nav-link active" data-toggle="tab" href="#contact" role="tab" aria-selected="true">Update Profile</a> </li>
            </ul>
            <div class="row">
              <!-- SIDE BAR -->
              <div class="col-lg-4">

                <!-- Company Information -->
                <div class="sidebar">

                  <!-- Heading for mobile Collapse -->
                  <h5 class="main-title margin-bottom-30">User Information</h5>
                  <div class="navbar-expand-lg">
                    <!-- Heading for mobile Collapse -->
                    <a class="collapsed main-title fr-mob" data-toggle="collapse" data-target="#cmpny-info" aria-expanded="false"> User Information </a>
                    <div class="collapse navbar-collapse" id="cmpny-info">
                      <div class="side-bar-indide">

                        <!-- Company Information -->
                        <div class="sidebar-information">
                          <ul class="single-category">
                            <li>
                              <h6 class="title">Name</h6>
                              <span class="subtitle">{{ Profile.name }}</span> </li>

                            <li>
                              <h6 class="title">Phone</h6>
                              <span class="subtitle">{{ Profile.number }}</span> </li>
                            <li>
                              <h6 class="title">Email</h6>
                              <div class="subtitle"><a href="#.">{{ Profile.email }}</a> </div>
                            </li>

                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <!-- Company Rating -->
                <div class="sidebar">
                  <h5 class="main-title margin-bottom-20">Rating</h5>
                  <div class="navbar-expand-lg">
                    <!-- Heading for mobile Collapse -->
                    <a class="collapsed main-title fr-mob" data-toggle="collapse" data-target="#cmpny-rtng" aria-expanded="false"> Rating </a>
                    <div class="collapse navbar-collapse" id="cmpny-rtng">
                      <div class="side-bar-indide">
                        <div class="sidebar-information">
                          <ul class="single-category com-rate">
                            <li>
                              <h6 class="title">Expertise:</h6>
                              <span class="subtitle"><i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fas fa-star-half-alt"></i> </span> </li>
                            <li>
                              <h6 class="title">Knowledge:</h6>
                              <span class="subtitle"><i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star-half-alt"></i> <i class="far fa-star"></i> <i class="far fa-star"></i> </span> </li>
                            <li>
                              <h6 class="title">Quality:</h6>
                              <span class="subtitle"><i class="fas fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fas fa-star-half-alt"></i> </span> </li>
                            <li>
                              <h6 class="title">Price:</h6>
                              <span class="subtitle"><i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star-half-alt"></i> <i class="far fa-star"></i> </span> </li>
                            <li>
                              <h6 class="title">Services:</h6>
                              <span class="subtitle"><i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star-half-alt"></i> </span> </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Tab Content -->
              <div class="col-lg-8">
                <div class="tab-content">

                  <!-- Contact -->
                  <div id="contact" class="tab-pane active">
                    <div class="profile-main">
                      <h3>Welcome! {{ Profile.name }}</h3>
                      <div class="profile-in">
                        <p>Hi! Update Your Profile. Updated Profile will get more views..</p>
                        <form action="" method="post" enctype="multipart/form-data" class="contact-company">
                            {% csrf_token %}
                          <ul class="row">
                            <li class="col-sm-6">
                                <label> Name</label>
                              {{ form.name }}
                            </li>

                              <li class="col-sm-6">
                                <label> Email</label>
                              {{ form.email }}
                            </li>

                              <li class="col-sm-12">
                                <label> Profile Title</label>
                              {{ form.profile_title }}
                            </li>

                              <li class="col-sm-4">
                                <label> Number</label>
                              {{ form.number }}
                            </li>
                              <li class="col-sm-4">
                                <label> DOB</label>
                              {{ form.dob }}
                            </li>

                              <li class="col-sm-4">
                                <label> Location</label>
                              {{ form.location }}
                            </li>
                              <li class="col-sm-12">
                                <label> About</label>
                              {{ form.about }}
                            </li>

                              <li class="col-sm-6">
                                <label> Degree</label>
                              {{ form.Degree }}
                            </li>

                              <li class="col-sm-6">
                                <label> Website</label>
                              {{ form.website }}
                            </li>


                              <li class="col-sm-6">
                                <label> Company</label>
                              {{ form.company }}
                            </li>

                              <li class="col-sm-6">
                                <label> Experience</label>
                              {{ form.experience }}
                            </li>

                          </ul>
                          <button type="submit" class="btn">Update Profile</button>
                        </form>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- WHAT OUR USERS SAY -->
  </div>
    {% endblock %}

connect/templates/add_company.html
{% extends 'base.html' %}

{% load static %}



{% block body %}

  <!-- Content -->
  <div id="content"> 
    
    <!-- Login Register -->
    <section class="login-register padding-top-100 padding-bottom-150">
      <div class="container"> 
        
        <!-- Payments Steps -->
        <div class="inside-log-reg">
              
              <!-- Nav Tabs -->
              <ul class="nav">
                  Welcome! {{ request.user.userdatabase_set.first.name }} ! <br>
                <li class=""> <a class="nav-link active " id="reg-tab" data-toggle="tab" href="#reg" role="tab" aria-selected="false">Start New Company</a> </li>
              </ul>
              
              <!-- Login Register Inside -->
              <div class="tab-content" id="myTabContent"> 

                <!-- Register -->
                <div class="tab-pane show active" id="reg" role="tabpanel" aria-labelledby="reg-tab">
                  <form action="" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                       <center><img id="output" style="border-radius: 50%;" width="200" height="200" /></center>
                    <ul class="row">

                        <li class="col-md-3">
                      </li>

                        <li class="col-md-6">
                        <label> Company  Logo *
                          {{ form.logo }}
                        </label>
                      </li>

                        <li class="col-md-3">
                      </li>

                      <!-- Name -->
                      <li class="col-md-6">
                        <label> Company  Name *
                          {{ form.name }}
                        </label>
                      </li>

                      
                      <!-- Name -->
                      <li class="col-md-6">
                        <label> Email Address *
                          {{ form.email }}
                           </label>
                      </li>

                        <li class="col-md-12">
                        <label>Title *
                          {{form.title}}
                        </label>
                      </li>

                      <li class="col-md-6">
                        <label> Contact Number *
                          {{form.number}}
                        </label>
                      </li>


                        <li class="col-md-6">
                        <label> Company Website *
                          {{form.website}}
                        </label>
                      </li>

                        <li class="col-md-12">
                        <label>Company Address *
                          {{form.address}}
                        </label>
                      </li>

                        <li class="col-md-12">
                        <label>Company Address on Map (Paste Embed Code Here) *<br>
                            change Width = 100%
                          {{form.map_embad}}
                        </label>
                      </li>




                      
                      <!-- LOGIN -->
                      <li class="col-md-12 text-center">
                        <button type="submit" class="btn">Register</button>
                      </li>
                    </ul>
                  </form>
                </div>


              </div>
         
        </div>
      </div>
    </section>
  </div>


    {% endblock %}

connect/templates/contact.html
{% extends 'base.html' %}
{% load static%}
{% block body%}
  <!-- Content -->
  <div id="content"> 
    
    <!-- Banner -->
    <section class="sub-bnr">
      <div class="container">
        <h2>Get in connect with us</h2>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Contact</li>
          </ol>
        </nav>
      </div>
    </section>
    
    <!-- Contact Info -->
    <section>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 padding-0">
            <div class="contact-info"> <h3 style="color:red;"><b>Developed By:</b></h3><span class="h4">Nihar Ranjan Mishra,</span>
              <ul>
                <li> <a href="#.">+91 7008117084 </a> </li>
                <li> <a href="#.">+91 9040208743</a> </li>
                <li> <a href="#.">niharmishra11@gmail.com </a> </li>
                <li>
                  <p>178 VSS Nagar, Bhubaneswar Odisha 751006 India</p>
                </li>
              </ul>
              
              <!-- Social Icon -->
              <div class="social-icon"> <a href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a> <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a> <a href="https://www.pinterest.com/"><i class="fab fa-pinterest-p"></i></a> <a href="https://www.youtube.com/"><i class="fab fa-youtube"></i></a> </div>
            </div>
          </div>
          
          <!-- Map -->
          <div class="col-lg-6 padding-0" style="backgroud-color:white;">
            <div class="map-block">
                  <img src="{% static 'images/nihar.jpg' %}" style="height:350px;width:350px;margin:150px;border-radius:25%">
            </div>
          </div>
        </div>
      </div>
    </section>

  </div>
{% endblock %}

connect/templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2 style="color:red;">Thank you </h2>
{{ msg }}
</body>
</html>